### ISSUE TITLE
seems doesn't work with webdriverio and cucumber

### ISSUE THREAD

**Issue by AlfredoMoretta** [alfonso-presa/soft-assert#3]
Hi,
the library will be very useful but doesn't work form with webdriverio v.6 and cucumber.Here is an example of my code:

```
let genericReturnLabel1 = '#addToCart1';

        softAssert($(genericReturnLabel1).isClickable()).to.be.true;
        try {
            flush();
        }
        catch (e) {
            expect(e.message).contain('i want an error');
        }
```
the error is :Cannot read property 'to' of undefined

if i'll use softExpect work properly but the test stops when fails and don't do other expectation ( i've tried this schema to find if is working : first Then throw and error, second Then is correct, third Then throw an error again)

thank you for your time

**Comment by alfonso-presa** [comment]
Hi Alfredo,

Are you using webdriverio's sync mode? Could you add a `console.log($(genericReturnLabel1).isClickable())` and check what is being printed? You might be missing an `await`.

Also, how are your initializing the `softAssert`?

**Comment by AlfredoMoretta** [comment]
Hi Alfonso,
first of all i want to thank you for your answer.Yes i'm using webdriverio in sync mode because i need it for our test.
the result of console log is "false" and is what i expect (i've two "Then" in my gherkin ,the first one i want that fails and second one no,but the test stop always on the first "Then" not using correctly softExpect and SoftAssert).
i've inizialize ,following your  example, SoftAssert and SofExpect in this way:

`const { proxy, flush } = require('@alfonso-presa/soft-assert');
const { expect, assert } = require('chai');
const softExpect = proxy(expect);
const softAssert = proxy(assert);`

what i'm doing wrong?
Thank you so much for the support.

**Comment by alfonso-presa** [comment]
Hi Alfredo,

I did a quick test with:

```javascript
const { proxy, flush } = require('@alfonso-presa/soft-assert');
const { expect } = require('chai');
const softExpect = proxy(expect);
const { When, Then} = require('cucumber');


When('something', function () {
    browser.url('https://webdriver.io/');
    softExpect($('div.buttons_1r9m > a:nth-child(1)').isClickable()).to.be.false;
});


Then('something different', function () {
    flush();
});
```

```gherkin
Feature: test

Scenario: test

    When something
    Then something different
```

```json
{
  "name": "test-softassert",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@alfonso-presa/soft-assert": "^0.6.0",
    "@wdio/cli": "^6.12.1",
    "chai": "^4.3.4"
  },
  "devDependencies": {
    "@wdio/local-runner": "^6.12.0",
    "@wdio/cucumber-framework": "^6.11.1",
    "@wdio/spec-reporter": "^6.11.0",
    "@wdio/sync": "^6.11.0",
    "chromedriver": "^97.0.2",
    "wdio-chromedriver-service": "^7.2.6"
  }
}
```

And the result is:
```
[chrome 97.0.4692.99 linux #0-0] Running: chrome (v97.0.4692.99) on linux
[chrome 97.0.4692.99 linux #0-0] Session ID: 81b5689232f543f2eb80cbf4c6f2f720
[chrome 97.0.4692.99 linux #0-0]
[chrome 97.0.4692.99 linux #0-0] test
[chrome 97.0.4692.99 linux #0-0]     test
[chrome 97.0.4692.99 linux #0-0]        ✓ When something
[chrome 97.0.4692.99 linux #0-0]        ✖ Then something different
[chrome 97.0.4692.99 linux #0-0]
[chrome 97.0.4692.99 linux #0-0] 1 passing (1.4s)
[chrome 97.0.4692.99 linux #0-0] 1 failing
[chrome 97.0.4692.99 linux #0-0]
[chrome 97.0.4692.99 linux #0-0] 1) test Then something different
[chrome 97.0.4692.99 linux #0-0] expected true to be false
[chrome 97.0.4692.99 linux #0-0] AssertionError: expected true to be false
```

So it seems to be perfectly working with WebdriverIO 6, and chais's expect..... There seems to be something wrong with your setup or code. Could you upload a reproducible example to a public github repository please?

**Comment by AlfredoMoretta** [comment]
thank you for the answer alfonso(sorry for the late of the answer but i've been very busy on the last period), i think i found the issue in my project (that not involve your library) and solved it.Hoping your soft assert and soft expect will be merged soon natively in webdriverio.
Thank you so much for your patience and your support.
